version: "3.9"

services:
  app:
    image: meie-checkin
    build: .
    container_name: meie-checkin-container
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=mingi_sala  # pane siia oma key
      - PORT=8080
    volumes:
      - ./data:/app/data
